apiVersion: v1
kind: Service
metadata:
  name: ms-controller-serv
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: https
  selector:
    app: ms-controller-app
  type: NodePort