apiVersion: v1
kind: PersistentVolume
metadata:
    name: pd-mongo
spec:
    storageClassName: "ssd"
    capacity:
        storage: 10G
    accessModes:
        - ReadWriteOnce
    gcePersistentDisk:
        pdName: mongo-disk
        fsType: ext4