apiVersion: v1
kind: Service
metadata:
  name: ms-db-serv
spec:
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: https
  selector:
    app: ms-db-app
  type: NodePort